### ISSUE TITLE
Impossible to override Redis serializer

### ISSUE THREAD

**Issue by acasademont** [doctrine/cache#150]
Hi! Even though we have the igbinary extension installed we don't want cache entries to be serialized with igbinary. Unfortunately, even though the phpredis client we use already has the OPT_SERIALIZER set, the RedisCache class ignores that and sets it to use igbinary if it detects the extension is present. Could a method be created to manually set which serializer method we want?

Thanks!

**Comment by dennis-hh** [comment]
+1. We are having issues with igbinary-serialized metadata, and want to use php's serializer instead.

**Comment by peteward** [comment]
Same here. 

We're using a pre-packaged version of php 7.0.6, igbinary and phpredis. The version of phpredis is compiled for igbinary so we cannot simply remove it in our hosting environment.

We see mapping errors whenever class metadata is retrieved from Redis such as:

```
[Doctrine\ORM\Mapping\MappingException]                                                    
  No mapping found for field 'X' on class 'Y'. 
```

or worse:

```
Segmentation Fault
```

The strange thing is that we _only_ see this on console using CLI. Using our web interface works without a problem.

The current workaround for us was to override RedisCache and force using `Redis::SERIALIZER_PHP`.

It feels like the problem here is really with igbinary, but I'm not sure.

Is anyone experiencing the same? I see a similar stories  https://github.com/phpredis/phpredis/issues/762 and https://github.com/snc/SncRedisBundle/issues/259

**Comment by griesi007** [comment]
Same behaviour as explained by @peteward for me - but only if php (PHP 7.0.6, Doctrine 2.5.4) is called from cli. Disabling redis as a doctrine cache backend on cli solves the problem as well as overwriting RedisCache to always use SERIALIZER_PHP.

**Comment by yellow1912** [comment]
`$redis->setOption(Redis::OPT_SERIALIZER, $this->getSerializerValue());`

I think right now the code always set the serializer, this leaves us in situations where we have to use serializer even when we don't want to. I think it should be up to the user to decide this.

**Comment by ostrolucky** [comment]
This would also fix https://github.com/doctrine/common/issues/155
