### ISSUE TITLE
Memcached adapter should replace spaces

### ISSUE THREAD

**Issue by lcobucci** [doctrine/cache#208]
As mentioned on https://github.com/doctrine/doctrine2/issues/4602 and  https://github.com/doctrine/doctrine2/pull/1424 Memcached has issues with keys that contains spaces and the ORM generates some of this keys for L2C.

However, as pointed by @Ocramius, the fix should be made on this package since only memcached has this issue.

**Comment by alpha-and-omega** [comment]
This should be fixed. I wasted hours trying to understand why this fails:

```
<?php
require_once (__DIR__."/vendor/autoload.php");
$memcached = new Memcached();
$memcached->addServer('localhost', 11211);
$cache = new \Doctrine\Common\Cache\MemcachedCache();
$cache->setMemcached($memcached);
var_dump( $cache->fetch("some key") );
var_dump($cache->save('some key', 'my_data'));
var_dump( $cache->fetch("some key") );
```
bool(false)
bool(false)
bool(false)

**Comment by gquemener** [comment]
Hello,

I ran into another issue related to memcached key limitation, so allow me to add my 2 cents (I could potentially fix both issues).

According to https://github.com/memcached/memcached/blob/master/doc/protocol.txt

> Keys
> ----
> 
> Data stored by memcached is identified with the help of a key. A key
> is a text string which should uniquely identify the data for clients
> that are interested in storing and retrieving it.  Currently the
> length limit of a key is set at 250 characters (of course, normally
> clients wouldn't need to use such long keys); the key must not include
> control characters or whitespace.

So there are a few steps required to sanitize the key before using it:
- Convert it into utf-8, if not already in this encoding
- Truncate it to 250 characters
- Strip whitespaces and control characters

One "simple" way of doing all that at once is to pass it to a hash function (as the FileCache adapter is doing).

Thus, I would suggest hashing (using fnv1a64 instead of sha256, because it is faster and offer a rather good non collision guarantee) the provided key before passing it to memcached.

This has the drawback of making manual memcached exploration harder, but fixes all the mentioned issues at once.

WDYT?

**Comment by lcobucci** [comment]
Let's revive this!

@gquemener I think that drawback is quite relevant, especially because it's not the same use case as the `FileCache` adapter.

**Comment by greg0ire** [comment]
Why not throw an exception instead?

**Comment by gquemener** [comment]
> Let's revive this!
> 
> @gquemener I think that drawback is quite relevant, especially because it's not the same use case as the `FileCache` adapter.

How different is the use case? 

> Why not throw an exception instead? (on next major, and for now deprecate this).
I would vote for consistency. There's only one place where "sanitization" is being performed (in the FileAdapter), which is why I suggested to do it in this adapter as well. Do you know if there's already an other adapter that has validation rule for the key format?

> Sanitization would mean collisions between `ab c` and `a bc`.
Correct, that's why I vote for hashing the given key without sanitization.

**Comment by greg0ire** [comment]
> I would vote for consistency.

I'm not a huge fan of consistency, but I think that's probably very personal. I've seen many bad things done in its name, that's why I usually try to use the new way rightaway, and deprecate the old way. Also, in the case of `FileCache` , we don't know what FS is in use, and they seem to have very different restrictions (see the comments about Windows), so without a clear set of rules it would be hard to do validation. In the case of memcache the rules are clear and well understood. It might make sense to have a `KeyValidatingCache` interface, and to test for it in `CacheProvider::save`, and call its method (`validateKey` ?) to validate keys when appropriate.

> Do you know if there's already an other adapter that has validation rule for the key format?

I personally don't know this, but I don't know that lib very well.

> This has the drawback of making manual memcached exploration harder, but fixes all the mentioned issues at once.

Maybe make the hashing conditional on the presence of forbidden chars, or the key being too long? That way reasonable people still have an explorable memcached (but then we might have bug reports about weird keys).

**Comment by gquemener** [comment]
After thinking about it, I think throwing an exception on invalid id format is a reasonable option. It keeps manual exploration possible.

However, being able to seamlessly switch between cache adapters is equally as important in my opinion. Unfortunately, I don't have any concrete example in mind, but a 3rd party library might use longer than 250 characters id in its cache layer, which would simply prevent usage of the memcached adapter (NB: today, these libraries are being informed that persistence went fine, although it didn't!).

I would see 3 options here (in order of personal preference):

1. Enable an adapter option (through the adapter constructor) to always activate memcached id transformation
2. Decorate the memcached adapter with some other yet-to-define adapter that transform the id
3. Transform the id on invalid id

This could totally be performed in a separate PR, after collecting some feedbacks, for instance.

IMO, the most urgent is to inform developers about the cases when cache is not being persisted correctly in memcached because the key was invalid (I will start working on this).

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
