### ISSUE TITLE
Allow extending namespace versioning methods

### ISSUE THREAD

**Issue by gskema** [doctrine/cache#263]
We want to disable namespace versioning for our cache:
- Namespace versioning adds an extra call to DB to get the current version
- deleteAll() may leave trash records without TTL in the database by simply incrementing namespace version

For these reasons, we want to disable namespace versioning. Right now it is very difficult because all the methods are private:
```
::getNamespaceCacheKey()
::getNamespaceId()
::getNamespaceVersion()
$namespaceVersion
```

The only possible way to disable this right now is to create a custom class or extend methods:

```
    protected function doFetch($id)
    {
        if ($this->getNamespaceCacheKey() === $id) {
            return false;
        }

        return $this->client->get($id);
    }

    private function getNamespaceCacheKey()
    {
        return sprintf(self::DOCTRINE_NAMESPACE_CACHEKEY, $this->getNamespace());
    }
```

If we made these methods/vars protected that would be much easier.

**Comment by jwage** [comment]
Instead of changing the methods to be protected, it might be better to add the ability to disable name spacing.

**Comment by Tobion** [comment]
Related #96

**Comment by holtkamp** [comment]
Encountered this situation as well.

>Instead of changing the methods to be protected, it might be better to add the ability to disable name spacing.

Well, I would argue that it *is* possible that:
- namespacing itself is used / useful, 
- versioning is not used/supported by certain CacheProviders

For example in an implementation of a CacheProvider using a relational database where each namespace has its own database table, but a certain cache entry has at most one row.

**Namespacing**
Imagine a scenario where multiple namespaces are used, think of:

- ApplicationCache
- MessageQueueCache
- ORMMetadataCache
- ORMQueryCache
- ORMResultCache
- ViewCache
- ...

These are all instances of a `ChainCache` with, for example: 
- an APC CacheProvider which requires the namespaces to function properly. 
- a database CacheProvider which uses the namespaces to determine the table name, but strips it from the actual cache identifiers

Concluding: namespacing is used here.

**Namespace versioning**
For the database CacheProvider, versioning is not used (the actual row is updated). For each first fetch of the database CacheProvider, a rather useless query is executed to determine the namespace version: No entry is found, so the namespace version defaults to `1`. 

Allowing a CacheProvider to override the namespace versioning related functionality as suggested in https://github.com/doctrine/cache/issues/263#issue-327589749 could easily overcome these disadvantages.

**Suggestion**
I would say making ```CacheProvider::getNamespaceVersion()``` protected would already help, since then a fixed version like '1' could be returned by default for specific CacheProviders, effectually _disabling versioning_, while _keeping namespacing_.

**Comment by alcaeus** [comment]
Closing as we're sunsetting this library. Please see #354 for more details.
